import os
from langchain_openai import ChatOpenAI
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from dotenv import load_dotenv

load_dotenv()

class RAGValidator:
    def __init__(self, use_gemini=True):
        """
        Initializes the LLM Validator. Defaults to Gemini if configured, else OpenAI.
        """
        if use_gemini and os.getenv("GOOGLE_API_KEY"):
            self.llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.1)
        elif os.getenv("OPENAI_API_KEY"):
            self.llm = ChatOpenAI(model="gpt-4o", temperature=0.1)
        else:
            raise ValueError("No valid API key found for RAG Validator. Set GOOGLE_API_KEY or OPENAI_API_KEY.")

        self.prompt_template = ChatPromptTemplate.from_messages([
            ("system", """You are a Senior Radiologist acting as a Trust-Aware Validator for an AI diagnostic system.
You will receive a Draft Radiology Report (generated by a Vision-Language Model) and a set of Hard Disease Probabilities (generated by a highly accurate CNN).

Your task is to mathematically and clinically reconcile the two:
1. If the Draft Report mentions a disease (e.g., 'signs of pneumonia') but the CNN probability for that disease is low (< 0.50), you MUST remove or correct that hallucination in the final report.
2. If the CNN probability for a disease is high (> 0.50) but the Draft Report missed it, you MUST add it to the final report.
3. Ensure the final report is clinically fluent, professional, and factually grounded in the CNN probabilities.

Output ONLY the final, corrected radiology report text. Do not output your reasoning steps."""),
            ("human", """
CNN Disease Probabilities:
{cnn_probs}

MediVLM Draft Report:
{draft_report}

Please generate the final, grounded radiology report:""")
        ])
        
        self.chain = self.prompt_template | self.llm

    def validate_report(self, draft_report, cnn_probs_dict):
        """
        Takes the raw text report and the dictionary of CNN probabilities,
        and returns the final grounded text report.
        """
        # Format the probabilities into a readable string
        probs_str = "\n".join([f"- {disease}: {prob*100:.1f}%" for disease, prob in cnn_probs_dict.items()])
        
        response = self.chain.invoke({
            "cnn_probs": probs_str,
            "draft_report": draft_report
        })
        
        return response.content
